import os
import django



os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')  # Substitua pelo caminho correto
django.setup()

from django.contrib.auth.models import User
from calculos.models import Substancia, Temperatura, Densidade
# print(User.objects.all())

# # Substitua 'admin' pelo nome de usuário do superusuário
# username = 'rodrigo'
# new_password = 'rodrigo'

# try:
#     user = User.objects.get(username=username)
#     user.set_password(new_password)
#     user.save()
#     print(f"Senha redefinida com sucesso para o usuário '{username}'!")
# except User.DoesNotExist:
#     print(f"Usuário '{username}' não encontrado.")

substancia = Substancia.objects.get(id=1)
temperatura = Temperatura.objects.get(id=1)

print(substancia)
print(temperatura)

Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=2.00,densidade=1.01180)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=3,densidade=1.0184)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=4,densidade=1.025)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=5,densidade=1.0317)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=6,densidade=1.0385)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=7,densidade=1.0453)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=8,densidade=1.0522)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=9,densidade=1.0591)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=10,densidade=1.0661)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=11,densidade=1.0731)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=12,densidade=1.0802)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=13,densidade=1.0874)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=14,densidade=1.0947)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=15,densidade=1.102)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=16,densidade=1.1094)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=17,densidade=1.1168)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=18,densidade=1.1234)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=19,densidade=1.1318)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=20,densidade=1.1394)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=21,densidade=1.1471)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=22,densidade=1.1548)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=23,densidade=1.1626)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=24,densidade=1.1704)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=25,densidade=1.1783)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=26,densidade=1.1862)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=27,densidade=1.1942)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=28,densidade=1.2023)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=29,densidade=1.2104)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=30,densidade=1.2185)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=31,densidade=1.2267)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=32,densidade=1.2349)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=33,densidade=1.2432)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=34,densidade=1.2515)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=35,densidade=1.2599)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=36,densidade=1.2684)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=37,densidade=1.2769)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=38,densidade=1.2855)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=39,densidade=1.2941)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=40,densidade=1.3028)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=41,densidade=1.3116)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=42,densidade=1.3205)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=43,densidade=1.3294)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=44,densidade=1.3384)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=45,densidade=1.3476)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=46,densidade=1.3569)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=47,densidade=1.3663)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=48,densidade=1.3758)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=49,densidade=1.3854)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=50,densidade=1.3951)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=51,densidade=1.4049)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=52,densidade=1.4148)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=53,densidade=1.4248)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=54,densidade=1.435)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=55,densidade=1.4453)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=56,densidade=1.4557)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=57,densidade=1.4662)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=58,densidade=1.4768)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=59,densidade=1.4875)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=60,densidade=1.4983)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=61,densidade=1.5091)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=62,densidade=1.52)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=63,densidade=1.531)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=64,densidade=1.5421)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=65,densidade=1.5533)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=66,densidade=1.5646)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=67,densidade=1.576)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=68,densidade=1.5874)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=69,densidade=1.5989)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=70,densidade=1.6105)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=71,densidade=1.6221)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=72,densidade=1.6338)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=73,densidade=1.6456)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=74,densidade=1.6574)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=75,densidade=1.6692)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=76,densidade=1.681)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=77,densidade=1.6927)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=78,densidade=1.7043)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=79,densidade=1.7158)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=80,densidade=1.727)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=81,densidade=1.7383)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=82,densidade=1.7491)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=83,densidade=1.7594)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=84,densidade=1.7693)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=85,densidade=1.7786)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=86,densidade=1.7872)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=87,densidade=1.7951)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=88,densidade=1.8022)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=89,densidade=1.8087)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=90,densidade=1.8144)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=91,densidade=1.8195)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=92,densidade=1.824)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=93,densidade=1.8279)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=94,densidade=1.8312)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=95,densidade=1.8337)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=96,densidade=1.8355)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=97,densidade=1.8364)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=98,densidade=1.8361)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=99,densidade=1.8342)
Densidade.objects.update_or_create(substancia=substancia,temperatura=temperatura,concentracao_percentual=100,densidade=1.8305)
