# Generated by Django 4.2 on 2024-12-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('concentration', models.FloatField()),
                ('volume', models.FloatField()),
                ('density', models.FloatField()),
            ],
        ),
    ]
