# Generated by Django 4.2 on 2024-12-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=50)),
                ('massa_molecular', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ppm_total', models.DecimalField(decimal_places=4, max_digits=10)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('densidade', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
