# Generated by Django 4.2 on 2024-12-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0002_substancia_delete_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substancia',
            name='densidade',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='substancia',
            name='massa_molecular',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
