# Generated by Django 4.2 on 2024-12-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0003_alter_substancia_densidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substancia',
            name='concentracao',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
