# Generated by Django 4.2 on 2024-12-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0004_substancia_concentracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substancia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
