# Generated by Django 4.2 on 2024-12-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0005_alter_substancia_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substancia',
            old_name='massa_molecular',
            new_name='massa_molar',
        ),
    ]
