# Generated by Django 4.2 on 2024-12-17 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0006_rename_massa_molecular_substancia_massa_molar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_celsius', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura (°C)')),
            ],
            options={
                'verbose_name': 'Temperatura',
                'verbose_name_plural': 'Temperaturas',
            },
        ),
        migrations.AlterModelOptions(
            name='substancia',
            options={'verbose_name': 'Substância', 'verbose_name_plural': 'Substâncias'},
        ),
        migrations.RemoveField(
            model_name='substancia',
            name='concentracao',
        ),
        migrations.RemoveField(
            model_name='substancia',
            name='densidade',
        ),
        migrations.RemoveField(
            model_name='substancia',
            name='massa_molar',
        ),
        migrations.RemoveField(
            model_name='substancia',
            name='ppm_total',
        ),
        migrations.RemoveField(
            model_name='substancia',
            name='temperatura',
        ),
        migrations.AddField(
            model_name='substancia',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='substancia',
            name='formula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fórmula Química'),
        ),
        migrations.AlterField(
            model_name='substancia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='substancia',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Substância'),
        ),
        migrations.CreateModel(
            name='Densidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentracao_percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Concentração (%)')),
                ('densidade', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Densidade (g/cm³)')),
                ('substancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='densidades', to='calculos.substancia')),
                ('temperatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='densidades', to='calculos.temperatura')),
            ],
            options={
                'verbose_name': 'Densidade',
                'verbose_name_plural': 'Densidades',
                'unique_together': {('substancia', 'temperatura', 'concentracao_percentual')},
            },
        ),
    ]
